name: Release AAR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build AAR
        run: ./gradlew :monocle:assembleRelease

      - name: Upload AAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: monocle-aar
          path: monocle/build/outputs/aar/*.aar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download AAR artifact
        uses: actions/download-artifact@v3
        with:
          name: monocle-aar
          path: ./monocle-aar

      - name: List files in monocle-aar
        run: ls -l ./monocle-aar

      - name: Rename AAR file
        run: mv ./monocle-aar/monocle-release.aar ./monocle-aar/monocle.aar

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload AAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./monocle-aar/monocle.aar
          asset_name: monocle.aar
          asset_content_type: application/zip